#!/bin/bash
# Debug resubmission script generated by DRIVER_HybridVar_analysis.sh.
# It can be rerun directly with:
#   qsub /lfs/h2/emc/stmp/ting.lei/3DVarAnalysis_PARALLEL/HybridVar.2026060910/logs/sub_verification.sh
#
# Original dependency from the automated workflow:
#   afterok:122374847.dbqs01

#PBS -A RRFS-DEV
#PBS -q dev
#PBS -l select=1:ncpus=128:ompthreads=8:mem=500G
#PBS -l walltime=01:00:00
#PBS -N na3km_verif
#PBS -j oe -o deb.log
#PBS -l place=excl

export envfile="/lfs/h2/emc/stmp/ting.lei/3DVarAnalysis_PARALLEL/HybridVar.2026060910/logs/HybridVar_run.env"
export PBS_NP="128"
export PBS_NUM_NODES="1"

echo "Debug verification job starting"
echo "  submit directory before cd: $(pwd)"
echo "  envfile=${envfile}"
echo "  PBS_NP=${PBS_NP}"
echo "  PBS_NUM_NODES=${PBS_NUM_NODES}"
source "${envfile}"
echo "  verifdir=${verifdir}"
echo "  anldir=${anldir}"

cd "/u/ting.lei/dr-3kmNA-parallel/RRFS_analysis_PARALLEL"
exec bash "/u/ting.lei/dr-3kmNA-parallel/RRFS_analysis_PARALLEL/scripts/exrrfs_compare_HybridVar_jedi_gsi.sh"
