#!/bin/bash
# Debug resubmission script generated by DRIVER_HybridVar_analysis.sh.
# It can be rerun directly with:
#   qsub /lfs/h2/emc/stmp/ting.lei/3DVarAnalysis_PARALLEL/HybridVar.2026062617/logs/sub_hybridvar.sh
#
# Original dependency from the automated workflow:
#   afterok:125579452.dbqs01:125579454.dbqs01

#PBS -A RRFS-DEV
#PBS -q debug 
#PBS -l select=62:mpiprocs=128:ompthreads=1:ncpus=128
#PBS -l walltime=00:30:00
#PBS -N na3km_hybrid
#PBS -j oe -o deb.log
#PBS -l place=vscatter:exclhost

export envfile="/lfs/h2/emc/stmp/ting.lei/3DVarAnalysis_PARALLEL/HybridVar.2026062617/logs/HybridVar_run.env"
export PBS_NP="128"
export PBS_NUM_NODES="62"

echo "Debug HybridVar job starting"
echo "  submit directory before cd: $(pwd)"
echo "  envfile=${envfile}"
echo "  PBS_NP=${PBS_NP}"
echo "  PBS_NUM_NODES=${PBS_NUM_NODES}"
source "${envfile}"
echo "  anldir=${anldir}"
echo "  HybridVaryaml=${HybridVaryaml}"

cd "/u/ting.lei/dr-3kmNA-parallel/RRFS_analysis_PARALLEL"
exec bash "/u/ting.lei/dr-3kmNA-parallel/RRFS_analysis_PARALLEL/scripts/exrrfs_analysis_HybridVar_jedi.sh"
